dogowner_app/config/routes.rb
Rails.application.routes.draw do

  root 'login#index'
  resources :users
  resources :dogs

  post "/login" => "login#create"
  get "/logout" => "login#destroy"
  get "/home" => "home#index"

end

dogowner_app/app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user



end

dogowner_app/app/models/registration_mapping.rb
class RegistrationMapping < ActiveRecord::Base
end

dogowner_app/app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

dogowner_app/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  belongs_to :roles
  has_many :dogs
  has_one :role

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(username,password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.role_name(role_id)
    puts "this is role_name from user model....#{role_id}"
    Role.find_by_id(role_id).name

  end
end

dogowner_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :authenticate_user, :except => [:index]

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    puts "authenticating user...."
    unless current_user
      redirect_to "/"
    end
  end

  helper_method :current_user
end

dogowner_app/app/controllers/dogs_controller.rb
class DogsController<ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy, :email]
  before_action :set_dog_registration

  def index
    @page_header = "Dogs List"
    if current_user.role_id == 1
      @dogs = Dog.all
    else
      @dogs = current_user.dogs()
    end

  end
  def new
    @dog = Dog.new
    @page_header = "Add New Dog"
    @page_button = "Add Dog"
  end
  def email
    @user = current_user
  end
  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      flash[:success] = "Dog has been successfully created."
      UserNotifier.send_email(current_user,@dog).deliver if $send_notification
      redirect_to @dog
    else
      flash[:error] = "Unable to add dog. Please try again."
      redirect_to :back
    end
  end
  def show
    @page_header = "Dog Details"
    @user = current_user
  end
  def edit
    @page_header = "Edit Dog"
    @page_button = "Update"
  end
  def update
    if @dog.update(dog_params)
      flash[:success] = "Dog Profile has been successfully updated."
      UserNotifier.send_email(current_user,@dog).deliver if $send_notification
    else
      flash[:error] = "Unable to update dog profile. Please try again."
    end
    redirect_to @dog
  end
  def destroy
    @dog.destroy
    redirect_to dogs_path
  end


  private

  def set_dog
    @dog = Dog.find(params[:id])
  end

  def dog_params
    reg_map = RegistrationMapping.find_by_months(params[:dog][:registration_months])
    user_id = current_user.id
    dog = Dog.find_by_name(params[:dog][:name])
    #user_id = dog.user_id unless dog.nil?
    $send_notification = false
    unless params[:dog][:registration_months].nil?
      reg_cost = reg_map.cost
      is_email_sent = true
      $send_notification = true
    end
    params.require(:dog).permit(:name,:breed,:birthdate,:is_registered,:registration_months).merge(registration_cost: reg_cost, is_email_sent: is_email_sent, user_id: user_id)
  end
  def set_dog_registration
    @reg_map = RegistrationMapping.all
  end
end

dogowner_app/app/controllers/home_controller.rb
class HomeController<ApplicationController
  def index

  end
end

dogowner_app/app/controllers/login_controller.rb
class LoginController<ApplicationController
  def index
    session[:user_id] = nil
    @page_header = "Please Login"
    flash = nil

  end
  def create
    @user = User.authenticate(params[:username],params[:password])
    if @user
      puts "user is authenticated..."
      session[:user_id] = @user.id
      redirect_to dogs_path
    else
      puts "user is NOT authenticated..."
      flash[:error] = "User NOT Authenticated. Please try again."
      redirect_to "/"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end
end

dogowner_app/app/controllers/users_controller.rb
class UsersController<ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @page_header = "Reports (click on a row to show Dog details)"
    @users = User.all

  end
  def new
    @page_header = "Please Register"
    @page_button = "Register"
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User has been successfully created."
        session[:user_id] = @user.id
        redirect_to "/"
    else
      flash[:error] = "Unable to register. Please try again."
      redirect_to :back
    end
  end
  def show
    @page_header = "User Profile"
  end
  def edit
    @page_header = "Manage Profile"
    @page_button = "Update"
  end
  def update
    if params[:user][:password].empty?
      user_update = @user.update_columns(user_params)
    else
      user_update = @user.update(user_params)
    end

    if user_update
      flash[:success] = "Profile has been successfully updated."
    else
      flash[:error] = "Unable to register. Please try again."
    end
    redirect_to @user
  end
  def destroy
    @user.destroy
      session[:user_id] = @user.id
      redirect_to "/"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    u = User.find_by_username(params[:user][:username])
    role_id = 2
    role_id = params[:user][:role_id] if current_user && current_user.role_id == 1
    params_require = params.require(:user).permit(:firstname,:lastname,:address,:email,:username)
    additional_params = {:role_id=>role_id}
    additional_params[:password] = params[:user][:password] unless params[:user][:password].empty?
    result = params_require.merge(additional_params) do |key, oldval, newval|
        oldval ||= {}
        oldval.merge newval
    end
    result.permit!
  end
end

dogowner_app/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-danger"
    end
  end
  def is_active?(link_path)
    current_page?(link_path) ? "active" : ""
  end


end

dogowner_app/app/views/dogs/_form.html.erb
    <%=form_for @dog do |f| %>

        <div class="form-group">
          <label for="name" class="col-sm-3 control-label text-right">Dog Name</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.text_field :name, :placeholder => "Please input dogname", :class => "form-control", :required => true %>
          </div>
        </div>

        <div class="form-group">
          <label for="breed" class="col-sm-3 control-label text-right">Breed</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.text_field :breed, :placeholder => "Please input breed", :class => "form-control", :required => true %>
          </div>
        </div>

        <div class="form-group">
          <label for="lastname" class="col-sm-3 control-label text-right">Date of Birth</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.date_field :birthdate, :placeholder => "Please input birthdate", :class => "form-control", :required => true %>
          </div>
        </div>

        <div class="form-group">
          <label for="isregistered" class="col-sm-3 control-label text-right">Is Registered?</label>
          <div class="col-sm-8 input-group">
            <%=f.check_box :is_registered,:onclick=>"toggle_radio(this)" %>
          </div>
        </div>

        <div class="form-group">
          <label for="registration_months" class="col-sm-3 control-label text-right">Months Registered</label>
          <div class="col-sm-8 input-group">
            <% @reg_map.each do |map| %>
                <%=f.radio_button :registration_months, "#{map.months}", :class=>"inline" %>
                <%= label "registration_months_#{map.months}", "#{map.months} months cost $#{map.cost}"%><br/>
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-9 col-sm-offset-2 text-center input-group">
            <input type="submit" class="btn btn-primary btn-block btn-success btn-lg" value="<%= @page_button %>"/>
          </div>
        </div>

        <%= render 'layouts/flash' %>
        <%= link_to 'Show Dog Details', @dog %> |
        <%= link_to 'Go to Dog List', dogs_path %>
    <%end%>

dogowner_app/app/views/dogs/edit.html.erb
<%= render 'form' %>

dogowner_app/app/views/dogs/index.html.erb
<table class="table table-striped table-condensed">
  <thead>
  <tr>
    <th>Name</th>
    <th>Breed</th>
    <th>Date of Birth</th>
    <th>Is Registered?</th>
    <th>Months Registered</th>
    <th>Registration Cost</th>
    <th>Owner</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @dogs.try(:each) do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.birthdate %></td>
        <td><%= dog.is_registered %></td>
        <td><%= dog.registration_months %></td>
        <td><%= dog.registration_cost %></td>
        <td><%= dog.user.username %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit/Register', edit_dog_path(dog) %></td>
        <td><%= link_to 'Delete', dog, method: :delete, data: { confirm: 'Are you sure you want to delete dog?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="form-group">
  <div class="col-md-12 control">
    <div style="border-top: 1px solid#888; padding-top:15px; margin-top:15px; font-size:85%" >
      <%= link_to "Add New Dog", new_dog_path %>
    </div>
  </div>
</div>

dogowner_app/app/views/dogs/new.html.erb
<%= render 'form' %>

dogowner_app/app/views/dogs/show.html.erb
<% if $send_notification %>
    <%= render 'layouts/email' %>
<% else %>
    <div class="form-group">
      <label for="name" class="col-sm-3 control-label text-right">Dog Name</label>
      <div class="col-sm-8 input-group">
        <%= @dog.name%>
      </div>
    </div>

    <div class="form-group">
      <label for="breed" class="col-sm-3 control-label text-right">Breed</label>
      <div class="col-sm-8 input-group">
        <%= @dog.breed%>
      </div>
    </div>

    <div class="form-group">
      <label for="lastname" class="col-sm-3 control-label text-right">Date of Birth</label>
      <div class="col-sm-8 input-group">
        <%= @dog.birthdate%>
      </div>
    </div>

    <div class="form-group">
      <label for="isregistered" class="col-sm-3 control-label text-right">Is Registered?</label>
      <div class="col-sm-8 input-group">
        <%= @dog.is_registered%>
      </div>
    </div>

    <div class="form-group">
      <label for="registration_months" class="col-sm-3 control-label text-right">Months Registered</label>
      <div class="col-sm-8 input-group">
        <%= @dog.registration_months%>&nbsp;
      </div>
    </div>
    <div class="form-group">
      <label for="registration_months" class="col-sm-3 control-label text-right">Registration Cost</label>
      <div class="col-sm-8 input-group">
        <%= @dog.registration_cost%>&nbsp;
      </div>
    </div>
<% end %>

<div class="form-group">
  <div class="col-sm-9">
    <%= render 'layouts/flash' %>
    <%= link_to 'Edit Dog', edit_dog_path(@dog) %> |
    <%= link_to 'Go to Dog List', dogs_path %>

  </div>
</div>
<br/><br/>

dogowner_app/app/views/home/index.html.erb
This is HOME!!!!

dogowner_app/app/views/layouts/_email.html.erb
<div class="form-group">
  <div class="col-sm-3">Hi <%= @user.username %>,</div>
</div>

<div class="form-group">
  <div class="col-sm-9 col-sm-offset-1">You have successfully registered your Dog for <%=@dog.registration_months %>&nbsp; months with the following details:</div>
</div>
<br/><br/>

<div class="form-group">
  <label for="name" class="col-sm-3 control-label text-right">Dog Name</label>
  <div class="col-sm-8 input-group">
    <%=@dog.name %>&nbsp;
  </div>
</div>

<div class="form-group">
  <label for="breed" class="col-sm-3 control-label text-right">Breed</label>
  <div class="col-sm-8 input-group">
    <%=@dog.breed %>&nbsp;
  </div>
</div>

<div class="form-group">
  <label for="birthdate" class="col-sm-3 control-label text-right">Date of Birth</label>
  <div class="col-sm-8 input-group">
    <%=@dog.birthdate %>&nbsp;
  </div>
</div>

<div class="form-group">
  <div class="col-sm-9 col-sm-offset-1">Please pay the registration cost amounting to $<%=@dog.registration_cost %>&nbsp; to bank account number 12-1234-1234-01.</div>
</div>
<br/><br/><br/>

<div class="form-group">
  <div class="col-sm-3">Sincerely,<br/>DOA Admin</div>
</div>
<br/><br/><br/>

dogowner_app/app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>

    <div class="col-sm-9 col-sm-offset-2 text-center input-group <%= flash_class(key.to_sym()) %>">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <%= value %>
    </div>
<% end %>

dogowner_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DogownerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="panel-body text-center alert-info">
  <div class="row col-xs-12 panel-body">
    <h1>DOA (Dog Owner Application)</h1>
  </div>
  <div class="divider"></div>
  <% if current_user%>
      <ul class="nav nav-pills">
        <li class="active"><%= link_to "Manage Dogs", dogs_path %></li>
        <li class="dropdown" style="float:right">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="glyphicon glyphicon-user"></i>  <%= current_user.username%><b class="caret"></b></a>
          <ul class="dropdown-menu" id="menu1">
            <li><%= link_to "View Profile", current_user %></li>
            <li><%= link_to "Manage Profile", edit_user_path(current_user) %></li>
            <% if current_user.role_id == 1 %>
                <li><%= link_to "Manage Users", users_path %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "Logout", logout_path%></li>
          </ul>
        </li>
      </ul>
  <% end %>

</div>
<div>&nbsp;</div>

<div class="scrollable-content panel-container">
  <div class="col-sm-10 col-sm-offset-1 alert-info">
    <div class="panel-body text-center">
      <div class="row col-xs-12 panel-body">
        <h3><%= @page_header%></h3>
      </div>
    </div>


    <div class="panel panel-default" style=" border: 2px solid transparent; border-radius: 25px; margin-top: -20px">

    <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

dogowner_app/app/views/login/index.html.erb
      <%=form_tag login_path do%>

          <div class="form-group">
            <label for="username" class="col-sm-3 control-label text-right">User Name</label>
            <div class="col-sm-8 input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
              <input type="text" name="username" class="form-control" id="username" required placeholder="Please input username"/>
            </div>
          </div>

          <div class="form-group">
            <label for="password" class="col-sm-3 control-label text-right">Password</label>
            <div class="col-sm-8 input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
              <input type="password" name="password" class="form-control" id="password" required placeholder="Please input password"/>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-9 col-sm-offset-2 text-center input-group">
                <input type="submit" class="btn btn-primary btn-block btn-success btn-lg" value="Login"/>
            </div>
          </div>

          <% flash.each do |key, value| %>

              <div class="col-sm-9 col-sm-offset-2 text-center input-group <%= flash_class(key.to_sym()) %>">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <%= value %>
              </div>
          <% end %>


          <div class="form-group">
            <div class="col-md-12 control">
              <div style="border-top: 1px solid#888; padding-top:15px; margin-top:15px; font-size:85%" >
                Don't have an account!
                <%= link_to "Sign Up Here", new_user_path %>
              </div>
            </div>
          </div>
      <%end%>

dogowner_app/app/views/user_notifier/send_email.html.erb
<%= render 'layouts/email' %>

dogowner_app/app/views/users/_form.html.erb
    <%=form_for @user do |f| %>

        <div class="form-group">
          <label for="username" class="col-sm-3 control-label text-right">User Name</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.text_field :username, :placeholder => "Please input username", :class => "form-control", :required => true %>
          </div>
        </div>

        <div class="form-group">
          <label for="password" class="col-sm-3 control-label text-right">Password</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.password_field :password, :placeholder => "Please input password", :class => "form-control", :required => @user.new_record? %>
          </div>
        </div>

        <div class="form-group">
          <label for="lastname" class="col-sm-3 control-label text-right">Password Confirmation</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.password_field :password_confirmation, :placeholder => "Please input password confirmation", :class => "form-control", :required => @user.new_record? %>
          </div>
        </div>

        <div class="form-group">
          <label for="firstname" class="col-sm-3 control-label text-right">First Name</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.text_field :firstname, :placeholder => "Please input firstname", :class => "form-control", :required => true %>
          </div>
        </div>

        <div class="form-group">
          <label for="lastname" class="col-sm-3 control-label text-right">Last Name</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%=f.text_field :lastname, :placeholder => "Please input lastname", :class => "form-control", :required => true %>
          </div>
        </div>

        <div class="form-group">
          <label for="email" class="col-sm-3 control-label text-right">Email</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-inbox"></i></span>
            <%=f.text_field :email, :placeholder => "Please input email", :class => "form-control", :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}'%>
          </div>
        </div>

        <div class="form-group">
          <label for="address" class="col-sm-3 control-label text-right">Postal Address</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-tower"></i></span>
            <%=f.text_field :address, :placeholder => "Please input postal address", :class => "form-control", :required => true %>
          </div>
        </div>

        <% if current_user && current_user.role_id == 1 %>
        <div class="form-group">
          <label for="address" class="col-sm-3 control-label text-right">Role</label>
          <div class="col-sm-8 input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-tower"></i></span>
            <%=f.text_field :role_id, :class => "form-control", :required => true %>
          </div>
        </div>
        <% end %>

        <div class="form-group">
          <div class="col-sm-9 col-sm-offset-2 text-center input-group">
            <input type="submit" class="btn btn-primary btn-block btn-success btn-lg" value="<%= @page_button %>"/>
          </div>
        </div>

        <%= render 'layouts/flash' %>
    <%end%>

    <div class="form-group">
    <div class="col-md-12 control">
      <div style="border-top: 1px solid#888; padding-top:15px; margin-top:15px; font-size:85%" >
        <% if @user.new_record?%>
            Already have an account!
            <%= link_to "Click Here", root_path %>
        <% else %>
            Unregister!
            <%= link_to "Click Here", user_path, :method=>"delete", data: {confirm: "Are you sure you want to unregister? (All data will be deleted)"} %>
        <% end %>
      </div>
      <%= render 'layouts/flash' %>

      <% if current_user && current_user.role_id == 1 %>
          <%= link_to 'Edit User', edit_user_path(@user) %> |
          <%= link_to 'Go to User List', users_path %>
      <% end %>
    </div>
    </div>

dogowner_app/app/views/users/edit.html.erb
<%= render 'form' %>

dogowner_app/app/views/users/index.html.erb
<table class="table table-striped table-condensed" style="border-collapse:collapse;">
  <thead>
  <tr>
    <th></th>
    <th>Username</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Role</th>
    <th colspan="2">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr data-toggle="collapse" data-target="<%= "#dog#{user.id}" %>" class="accordion-toggle">
        <td>+</td>
        <td><%= user.username %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.address %></td>
        <td><%= user.email %></td>
        <td><%= User.role_name(user.role_id) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure you want to delete user?' } %></td>
      </tr>
      <tr >
        <td colspan="9" class="hiddenRow">
          <div class="accordian-body collapse col-sm-9 col-sm-offset-2" id="<%= "dog#{user.id}" %>">
            <table class="table">
              <thead>
              <tr>
                <th>Name</th>
                <th>Breed</th>
                <th>Date of Birth</th>
                <th>Reg Months </th>
                <th>Reg Cost </th>
              </tr>
              </thead>
              <tbody>
              <% user.dogs.where(:is_registered=>true).try(:each) do |dog| %>
                  <tr>
                    <td><%= dog.name %></td>
                    <td><%= dog.breed %></td>
                    <td><%= dog.birthdate %></td>
                    <td><%= dog.registration_months %></td>
                    <td>$<%= dog.registration_cost%></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="form-group">
  <div class="col-md-12 control">
    <div style="border-top: 1px solid#888; padding-top:15px; margin-top:15px; font-size:85%" >
      <%= link_to "Add New User", new_user_path %>
    </div>
  </div>
</div>

dogowner_app/app/views/users/new.html.erb
<%= render 'form' %>

dogowner_app/app/views/users/show.html.erb
          <div class="form-group">
            <label for="username" class="col-sm-3 control-label text-right">User Name</label>
            <div class="col-sm-8 input-group">
              <%=@user.username %>&nbsp;
            </div>
          </div>

          <div class="form-group">
            <label for="firstname" class="col-sm-3 control-label text-right">First Name</label>
            <div class="col-sm-8 input-group">
              <%=@user.firstname %>&nbsp;
            </div>
          </div>

          <div class="form-group">
            <label for="lastname" class="col-sm-3 control-label text-right">Last Name</label>
            <div class="col-sm-8 input-group">
              <%=@user.lastname %>&nbsp;
            </div>
          </div>

          <div class="form-group">
            <label for="email" class="col-sm-3 control-label text-right">Email</label>
            <div class="col-sm-8 input-group">
              <%=@user.email %>&nbsp;
            </div>
          </div>

          <div class="form-group">
            <label for="address" class="col-sm-3 control-label text-right">Postal Address</label>
            <div class="col-sm-8 input-group">
              <%=@user.address %>&nbsp;
            </div>
          </div>

          <div class="form-group">
            <label for="address" class="col-sm-3 control-label text-right">Role</label>
            <div class="col-sm-8 input-group">
              <%=User.role_name(@user.role_id) %>&nbsp;
            </div>
          </div>



          <div class="form-group">
            <div class="col-sm-9">
              <%= render 'layouts/flash' %>
              <% if current_user.role_id == 1 %>
                  <%= link_to 'Edit User', edit_user_path(@user) %> |
                  <%= link_to 'Go to User List', users_path %>
              <% end %>

            </div>
          </div>
          <br/><br/>